version: '3'
services:
  phinx.app:
    build:
      context: phinx
      dockerfile: runtimes/7.4/Dockerfile
      args:
        SYSTEMUSERID: ${SYSTEMUSERID:-1000}
        SYSTEMUSERNAME: ${SYSTEMUSERNAME:-phinx}
        SYSTEMGROUPID: ${SYSTEMGROUPID:-1000}
        SYSTEMGROUPNAME: ${SYSTEMGROUPNAME:-phinx}
    ports:
      - ${APP_PORT:-80}:8080
    environment:
      SYSTEMUSERID: ${SYSTEMUSERID:-1000}
    volumes:
      - '.:/var/www/app'
    networks:
      - phinx
    depends_on:
      - mysql

  mysql:
    image: 'mysql:8.0'
    ports:
      - ${FORWARD_DB_PORT:-3306}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_DATABASE: ${DB_DATABASE:-mysql_db}
      MYSQL_USER: ${DB_USERNAME:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'phinxmysql:/var/lib/mysql'
    networks:
      - phinx

networks:
  phinx:
    driver: bridge

volumes:
  phinxmysql:
    driver: local